### ISSUE TITLE
ul and ol styling was edited for markdown, but effects whole app

### ISSUE THREAD

**Issue by seann1** [chingu-voyages/v37-bears-team-14#79]
**Describe the problem**
ul and ol styling was edited for markdown, but effects whole app. Bullet points appear where they shouldn't

**Actual behavior**
ul and ol elements should have default tailwind styling except for when they are inside of markdown elements.

**Expected behavior**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or gifs to help explain your problem.

**Your Environment:**
 - Your browser & its version
 - Any other software that may impact this issue

**Additional Information**

**Comment by mtso** [comment]
Closed in #80
